### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by mallikharjunrao** [PhanNN/postman-combine#1]
I am Getting the following excpetion when i ran the following command. I am trying to combine 2 postman collections.

is there any solution?

**node index.js -dest output.json -f datasets.json regression.json**

Input:
   datasets.json
   regression.json
Output: output.json
(node:15096) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileCallback (C:\Users\mallikarjunrao.chiru\Desktop\index.js:31:24)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:15096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PhanNN** [comment]
@mallikharjunrao : Could you give me 2 input files and your node version?

**Comment by PhanNN** [comment]
@mallikharjunrao : Did you change something in template.json file?

**Comment by PhanNN** [comment]
I close this issue. If it still exist, please create new one :)
